# Generated by Django 3.1 on 2022-03-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='team',
            field=models.CharField(choices=[('SpaceValkyrie', 'SpaceValkyrie'), ('チームカズシ', 'チームカズシ'), ('こぐま座', 'こぐま座'), ('チームユウシ', 'チームユウシ'), ('アノマロ', 'アノマロ'), ('スペースエクスプローラーズ', 'スペースエクスプローラーズ'), ('12時20分', '12時20分'), ('にゅうさんきん', 'にゅうさんきん'), ('PISTOL STAR', 'PISTOL STAR'), ('PUMA', 'PUMA'), ('Iriko', 'Iriko'), ('流れ星★', '流れ星★'), ('OSHIRO', 'OSHIRO'), ('H', 'H'), ('TOMATO人', 'TOMATO人'), ('SFK', 'SFK'), ('ロワン', 'ロワン'), ('はると', 'はると'), ('素数少年', '素数少年')], max_length=50),
        ),
    ]
